name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
gitleaks:
  name: Scan secrets with Gitleaks
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v2
      with:
        args: detect --report-path gitleaks-report.json --report-format json --exit-code 1

    - name: Upload Gitleaks report
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.json

  codeql:
    name: Scan code with CodeQL
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python  # change to match your repo

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
