name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gitleaks:   # 👈 needs to be indented under "jobs"
    name: Scan secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --report-path gitleaks-report.json --report-format json --exit-code 1

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

  codeql:   # 👈 must be at same level as gitleaks
    name: Scan code with CodeQL
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript  # change to match your repo

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
